export const THEMES = {
  dark: {
    name: 'Dark',
    bgPrimary: 'bg-gray-950',
    bgSecondary: 'bg-gray-900',
    textPrimary: 'text-white',
    textSecondary: 'text-gray-400',
    borderColor: 'border-gray-700',
    accentColor: 'bg-blue-600',
    accentHover: 'hover:bg-blue-500',
  },
  light: {
    name: 'Light',
    bgPrimary: 'bg-white',
    bgSecondary: 'bg-gray-50',
    textPrimary: 'text-black',
    textSecondary: 'text-gray-700',
    borderColor: 'border-gray-400',
    accentColor: 'bg-blue-500',
    accentHover: 'hover:bg-blue-600',
  },
  slate: {
    name: 'Slate',
    bgPrimary: 'bg-slate-900',
    bgSecondary: 'bg-slate-800',
    textPrimary: 'text-slate-100',
    textSecondary: 'text-slate-400',
    borderColor: 'border-slate-700',
    accentColor: 'bg-indigo-600',
    accentHover: 'hover:bg-indigo-500',
  },
  nord: {
    name: 'Nord',
    bgPrimary: 'bg-[#2e3440]',
    bgSecondary: 'bg-[#3b4252]',
    textPrimary: 'text-[#eceff4]',
    textSecondary: 'text-[#d8dee9]',
    borderColor: 'border-[#434c5e]',
    accentColor: 'bg-[#88c0d0]',
    accentHover: 'hover:bg-[#81a1c1]',
  },
  dracula: {
    name: 'Dracula',
    bgPrimary: 'bg-[#282a36]',
    bgSecondary: 'bg-[#21222c]',
    textPrimary: 'text-[#f8f8f2]',
    textSecondary: 'text-[#6272a4]',
    borderColor: 'border-[#44475a]',
    accentColor: 'bg-[#ff79c6]',
    accentHover: 'hover:bg-[#ff85d5]',
  },
  gruvbox: {
    name: 'Gruvbox',
    bgPrimary: 'bg-[#282828]',
    bgSecondary: 'bg-[#3c3836]',
    textPrimary: 'text-[#ebdbb2]',
    textSecondary: 'text-[#a89984]',
    borderColor: 'border-[#504945]',
    accentColor: 'bg-[#fe8019]',
    accentHover: 'hover:bg-[#fabd2f]',
  },
  girly: {
    name: 'Girly',
    bgPrimary: 'bg-pink-50',
    bgSecondary: 'bg-rose-100',
    textPrimary: 'text-rose-950',
    textSecondary: 'text-rose-900',
    borderColor: 'border-rose-400',
    accentColor: 'bg-pink-500',
    accentHover: 'hover:bg-pink-600',
  },
  cyberpunk: {
    name: 'Cyberpunk',
    bgPrimary: 'bg-[#0a0e27]',
    bgSecondary: 'bg-[#1a1f3a]',
    textPrimary: 'text-[#0ff0fc]',
    textSecondary: 'text-[#d60dff]',
    borderColor: 'border-[#ff006e]',
    accentColor: 'bg-[#ff006e]',
    accentHover: 'hover:bg-[#ff3385]',
  },
  coder: {
    name: 'Coder',
    bgPrimary: 'bg-[#0d0d0d]',
    bgSecondary: 'bg-[#1a1a1a]',
    textPrimary: 'text-[#00ff00]',
    textSecondary: 'text-[#00aa00]',
    borderColor: 'border-[#003300]',
    accentColor: 'bg-[#00ff00]',
    accentHover: 'hover:bg-[#33ff33]',
  },
};

export const DEFAULT_THEME = 'dark';
